### ISSUE TITLE
"Mapping::ModelSpec::DateMapping can map with timezone option" test fails under Ruby 3

### ISSUE THREAD

**Issue by matoro** [ioquatix/mapping#1]
Hi, this test does not work under Ruby 3.0 or 3.1.  It works under 2.6 and 2.7.

```
>>> Test phase: dev-ruby/mapping-1.1.1
 * Running test phase for ruby26 ...
.............

Finished in 0.06143 seconds (files took 0.51584 seconds to load)
13 examples, 0 failures
                                                                                                                               [ ok ]
 * Running test phase for ruby27 ...
.............

Finished in 0.12879 seconds (files took 1.29 seconds to load)
13 examples, 0 failures
                                                                                                                               [ ok ]
 * Running test phase for ruby30 ...
..F..........

Failures:

  1) Mapping::ModelSpec::DateMapping can map with timezone option
     Failure/Error:
       map(Time) do |date, offset: nil|
        if offset
                date.localtime(offset)
        else
                date
        end

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./spec/mapping/model_spec.rb:25:in `block in <class:DateMapping>'
     # ./lib/mapping/model.rb:60:in `map'
     # ./spec/mapping/model_spec.rb:42:in `block (2 levels) in <module:ModelSpec>'

Finished in 0.08079 seconds (files took 0.52382 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/mapping/model_spec.rb:41 # Mapping::ModelSpec::DateMapping can map with timezone option
```

**Comment by ioquatix** [comment]
Fixed in v1.1.2.

Apologies for the long delay.
